[package]
name = "quiz-game"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-program = "2.2.1"
borsh = "1.5.7"
borsh-derive = "0.10.3"
thiserror = "1.0.40"
ephemeral-rollups-sdk = "0.2.5"

[lib]
crate-type = ["cdylib", "lib"]